version: 2

updates:
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "cargo"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope
